ZSH_BASE=$HOME/dotfiles

source $ZSH_BASE/antigen/antigen.zsh

# Use Oh My ZSH
antigen use oh-my-zsh

# Plugins
antigen bundle git
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-history-substring-search
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle z

# Node
antigen bundle lukechilds/zsh-nvm
antigen bundle npm

# "pure" theme
antigen bundle mafredri/zsh-async
antigen bundle sindresorhus/pure

# Apply stuff
antigen apply

